---
fluxbb_domain: bbs.archlinux.org
fluxbb_dir: /srv/http/fluxbb

fluxbb_cookie_name: flux_cookie_eezohm0o
fluxbb_funnyquestion_hash: aixuGahCh4eng3bu
fluxbb_version: 8d95fbd95b82dd0a996603cc28f79b36b8e54253
