---

- name: set up nginx
  template: src=nginx.d.conf.j2 dest=/etc/nginx/nginx.d/mailman.conf owner=root group=root mode=644
  notify:
    - reload nginx
  tags:
    - nginx

- name: make nginx log dir
  file: path=/var/log/nginx/{{ mailman_domain }} state=directory owner=root group=root mode=0755
  when: archweb_site
  tags:
    - nginx
