---

- name: restart networkd
  systemd:
    name: systemd-networkd
    state: restarted
    daemon_reload: true

- name: restart journald
  systemd:
    name: systemd-journald
    state: restarted
    daemon_reload: true

- name: systemd daemon-reload
  systemd:
    daemon_reload: true

- name: restart syslog-ng
  service: name=syslog-ng@default state=restarted

- name: restart systemd-swap
  service: name=systemd-swap state=restarted
