---

matrix_nginx_config:
  - name: federation_reader
    port: 8011
    locations:
      - "~ ^/_matrix/federation/v1/event/"
      - "~ ^/_matrix/federation/v1/state/"
      - "~ ^/_matrix/federation/v1/state_ids/"
      - "~ ^/_matrix/federation/v1/backfill/"
      - "~ ^/_matrix/federation/v1/get_missing_events/"
      - "~ ^/_matrix/federation/v1/publicRooms"
      - "~ ^/_matrix/federation/v1/query/"
      - "~ ^/_matrix/federation/v1/make_join/"
      - "~ ^/_matrix/federation/v1/make_leave/"
      - "~ ^/_matrix/federation/v1/send_join/"
      - "~ ^/_matrix/federation/v2/send_join/"
      - "~ ^/_matrix/federation/v1/send_leave/"
      - "~ ^/_matrix/federation/v2/send_leave/"
      - "~ ^/_matrix/federation/v1/invite/"
      - "~ ^/_matrix/federation/v2/invite/"
      - "~ ^/_matrix/federation/v1/query_auth/"
      - "~ ^/_matrix/federation/v1/event_auth/"
      - "~ ^/_matrix/federation/v1/exchange_third_party_invite/"
      - "~ ^/_matrix/federation/v1/user/devices/"
      - "~ ^/_matrix/federation/v1/get_groups_publicised$"
      - "~ ^/_matrix/key/v2/query"
      - "~ ^/_matrix/federation/v1/send/"  # Don't load balance
  - name: media_repository
    port: 8013
    locations:
      - "~ ^/_matrix/media/"
      - "~ ^/_synapse/admin/v1/purge_media_cache$"
      - "~ ^/_synapse/admin/v1/room/.*/media.*$"
      - "~ ^/_synapse/admin/v1/user/.*/media.*$"
      - "~ ^/_synapse/admin/v1/media/.*$"
      - "~ ^/_synapse/admin/v1/quarantine_media/.*$"
  - name: homeserver
    port: 8008
    locations:
      - "/_matrix"
      - "/_synapse"
