---

- name: setup aur-dev.archlinux.org
  hosts: aur-dev.archlinux.org
  remote_user: root
  roles:
    - { role: common }
    - { role: tools }
    - { role: sshd, sshd_enable_includes: true }
    - { role: root_ssh }
    - { role: certbot }
    - { role: nginx }
    - { role: mariadb, mariadb_query_cache_type: '0', mariadb_innodb_file_per_table: true }
    - { role: sudo }
    - { role: php_fpm, php_extensions: ['iconv', 'memcached', 'mysqli', 'pdo_mysql'], zend_extensions: ['opcache'] }
    - { role: memcached }
    - { role: uwsgi }
    - { role: borg_client, tags: ["borg"] }
    - { role: postfix, postfix_relayhost: "mail.archlinux.org" }
    - { role: fail2ban }
    - { role: aurweb, aurweb_domain: 'aur-dev.archlinux.org', aurweb_version: 'pu' }
    - { role: prometheus_exporters }
