---

- name: setup bugs.archlinux.org
  hosts: bugs.archlinux.org
  remote_user: root
  roles:
    - { role: common }
    - { role: tools }
    - { role: sshd }
    - { role: root_ssh }
    - { role: certbot }
    - { role: nginx }
    - { role: mariadb, mariadb_query_cache_type: '0', mariadb_innodb_file_per_table: true }
    - { role: sudo }
    - { role: php7_fpm, php_extensions: ['mysqli'], zend_extensions: ['opcache'] }
    - { role: flyspray }
    - { role: borg_client, tags: ["borg"] }
    - { role: postfix, postfix_relayhost: "mail.archlinux.org" }
    - { role: fail2ban }
    - { role: prometheus_exporters }
